### ISSUE TITLE
how to sync bbdb url field?

### ISSUE THREAD

**Issue by unhammer** [skarra/ASynK#103]
I've always put home pages in the url field of BBDB (newline-separated). I tried doing 

`config['db_config']['bb']['notes_map']['web_home_re'] = 'url'
`
but then ASynK somehow changes all the `url` fields into saying `Web-00-Home`. What's the standard way of doing this?

**Comment by skarra** [comment]
Yes; this is a bug. Can you try out this branch to see if this fixes your issue: https://github.com/skarra/ASynK/tree/issue/103

**Comment by unhammer** [comment]
It's not longer creating `Web-00-Home` fields, but I'm not seeing the url's synced to my Owncloud. 

The logs say `DEBUG:root:PIMDB cd does not have email_domains.
DEBUG:root:PIMDB cd does not have postal_map
DEBUG:root:PIMDB cd does not have notes_map
DEBUG:root:PIMDB cd does not have phones_map
` – should I have something about urls on the carddav side of the config too?

**Comment by skarra** [comment]
I see... I just remembered I did not complete support for all the fields on the carddav side, including website urls. I have created a new issue to track that here: https://github.com/skarra/ASynK/issues/104

I am busy with other things, and may not be able to get to #104 for at least 6-8 weeks. You might need a workaround in the mean time... I suggest you remove the customisation in your config.py so that the url fields in your BBDB are saved verbatim to a notes field in your ownCloud; at least you can view it there as a blob. If you do not do that there is a risk of losing this information.
