### ISSUE TITLE
phone number format NANP error after creation in bbdb then sync

### ISSUE THREAD

**Issue by ian-kelling** [skarra/ASynK#127]
I initially created a bbdb file by syncing from carddav. Then I created a contact in bbdb:
```
["Jane" "Doe" nil nil nil (["cell" 444 222 9999 0]) (["home" ("x st") "x town" "CA" "90210" "USA"]) nil nil "90f9f89c-6620-4f59-93c8-b9c5e013c769" "2018-11-17 22:13:48 +000
```

synced with a carddav, then the bbdb record has a string for the phone number:
```
["Jane" "Doe"  nil nil nil (["cell" "+1 444 222 9999 0"]) (["home" ("x st") "x town" "CA" "90210" "USA"]) nil ((bbdb-id . "4c79bc0f-eab8-11e8-9223-0026b6f7d4d8") (creation-date . "2018-11-17 22:13:48 +0000") (timestamp . "2018-11-17 22:29:57 +0000") (asynk:main:cd . "32c56938ca455d8a9d93495bb11a2e9e")  ) "4c79bc0f-eab8-11e8-9223-0026b6f7d4d8" "2018-11-17 22:13:48 +0000" "2018-11-17 22:29:57 +0000"  nil]
```
And then bbdb fails to parse the file with this error
"bbdb-phone-string: Not an NANP number: Other"

"Other" is the name of the type of phone record in an earlier record that also got changed.

I'm using bbdb 20180907.311 from melpa and ASynK v2.3.1 (Sat Jun 9 10:23:46 2018)

**Comment by skarra** [comment]
If I copy paste the second record with the phone number in an otherwise empty bbdb file (format v9) and open that in BBDB V3.2 in Emacs 25.1.1 on Mac, it opens just fine. See screenshot below. Also he first record in your note above is incomplete.

Can you share details of your file format version, BBDB version and Emacs version?

![image](https://user-images.githubusercontent.com/633395/48888855-d49c2a80-ede8-11e8-884b-f2773faceff7.png)

**Comment by skarra** [comment]
Please reopen if you are still seeing a bug.
